languageCode = "ru"
defaultContentLanguage = "ru"
title = "Пока ты спал"
baseURL = "https://sleeptrip.ru/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # set below parameter to define a favicon
 favicon = "https://s3.regru.cloud/sleeptrip-dev/images/favicon.ico"
  # set to change date format
 dateFormat = "2 January 2006"
 backgroundPath = "images/desktop.webp"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#    showFirstLast = false
 
# [languages]
# [languages.en]
 # languageName = "English"

